apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-gateway-config
data:
  application-dev.yml: |
    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: backend-user
                uri: http://backend-user-service:8080
                predicates:
                  - Path=/api/users/**
                filters:
                  - AddAuthenticationHeader