apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-gateway-config
data:
  application-dev.yml: |
    spring:
      cloud:
        gateway:
          mvc:
            routes:
              - id: backend-user
                uri: http://backend-user-service:8080
                predicates:
                  - Path=/api/users/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-study-chat
                uri: http://backend-chat-service:8080
                predicates:
                  - Path=/api/chat/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-study-notification
                uri: http://backend-notification-service:8080
                predicates:
                  - Path=/api/notifications/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-study
                uri: http://backend-study-service:8080
                predicates:
                  - Path=/api/studies/**
                filters:
                  - AddAuthenticationHeader
              - id: backend-study-member
                uri: http://backend-study-member-service:8080
                predicates:
                  - Path=/api/study-members/**
                filters:
                  - AddAuthenticationHeader