apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend-gateway
  template:
    metadata:
      labels:
        app: backend-gateway
    spec:
      containers:
        - name: backend-gateway
          image: namsangwon/studyhub-api-gateway:0.0.1
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: backend-gateway-config-volume
              readOnly: true
            - mountPath: /etc/secret/jwt
              name: jwt-secret-volume
              readOnly: true
            - mountPath: /etc/secret/redis
              name: redis-secret-volume
              readOnly: true
      volumes:
        - name: backend-gateway-config-volume
          configMap:
            name: backend-gateway-config
            items:
              - key: application-dev.yml
                path: application-dev.yml
        - name: jwt-secret-volume
          secret:
            secretName: jwt-secret
            items:
              - key: application-jwt.yml
                path: application-jwt.yml
        - name: redis-secret-volume
          secret:
            secretName: redis-secret
            items:
              - key: application-redis.yml
                path: application-redis.yml
